/**
 * @name         Subreddit Community Semantic Analysis
 * @description  Creating a data visualization that shows the most used words of each subreddit and how much they relate to one another 

 * @authour      James Lian
 * Created:      8-Oct-2025
 * Updated:      13-Oct-2025
*/

let wordBlobs = 10;

let balls = [];
let metaballs = [];

let redditDataTable;
let globalWordVectors = {}
let subreddits = {};

let currSubredditSelection = {};

// UI VARIABLES
let title;
let frameCount = 0;
let blobSlider;
let blobSliderLabel;
let blobbiness;
let blobbinessLabel;
let pixelSpacing;
let pixelSpacingLabel;

// DATA HANDLING FUNCTIONS
function preload() {    
    // retrieving the 20 most popular words from some of the most popular subreddits, including the word vectors!
		// word vectors were generated by yours truly (James) through a custom Python script with a pretrained gloVe text embedding model
    redditDataTable = loadTable("subreddits.csv", "csv", "header", setupData);
}

/** 
	* @method setupData
	* @description Data preparation function that stores all necessary data inside the redditDataTable
*/
function setupData() {
		console.log("Setting up data for " + str(redditDataTable.getRowCount()) + " rows");
		let rows = redditDataTable.getRows();
		// iterating through all the rows
    for (let i = 0; i < redditDataTable.getRowCount(); i++) {
        let row = rows[i];
				// storing important columns in variables
        let subreddit = row.getString("subreddit");
        let word = row.getString("word");
				
				// store all subreddits in the subreddits variable
        if (subreddits.hasOwnProperty(subreddit) === false) {
            subreddits[row.getString("subreddit")] = [];
        }

				// storing the relative vectors of the word (within their particular subreddit)
        let x = row.getString("relative_vector_x");
        let y = row.getString("relative_vector_y");
        let z = row.getString("relative_vector_z");
        // if word vectors are not invalid
        if (x !== "None" && y !== "None" && z !== "None") {
            x = float(x);
						y = float(y);
						z = float(z);
						subreddits[row.getString("subreddit")].push({
                "word": word,
                "relative_vector": [x, y, z], 
                "avg_score": int(row.getString("avg_score"))
            });
						
						// storing the global vectors of the word (within a global context - how they relate to ALL other words in ALL other subreddits in the .csv file)
            let globX = float(row.getString("absolute_vector_x"));
            let globY = float(row.getString("absolute_vector_y"));
            let globZ = float(row.getString("absolute_vector_z"));
            globalWordVectors[word] = [globX, globY, globZ];
        }
    }
} 

/** 
	* @method randomDataSelection
	* @description Randomly selects a subreddit and a randomized selection of its top words
*/
function randomDataSelection() {
		currSubredditSelection = {};

		// randomly select a subreddit and check if it has enough data points
		let selected = random(Object.keys(subreddits));
		if (subreddits[selected].length >= wordBlobs) {
				// shuffle the words and take the first few
				currSubredditSelection[selected] = shuffle(subreddits[selected]).slice(0, wordBlobs);
		}
}

/** 
	* @method resetMetaball
	* @description Resets the metaball parameters and generates a new metaball based on a randomized subreddit and its most popular words
*/
function resetMetaball() {
		// clear all the BlobSpheres inside the metaball's scene property
		metaball.scene.length = 0;
		
		// randomly select subreddit + words
		randomDataSelection();
		for (let subreddit in currSubredditSelection) {
				// instantiate new BlobSphere object as ball with relative_vector as its position prop and the avg_score of the word as its radius
				for (let word of currSubredditSelection[subreddit]) {
            let ball = new BlobSphere({
                x: word.relative_vector[0],
                y: word.relative_vector[1],
                z: word.relative_vector[2],
                radius: word.avg_score,
								text: word.word,
								// colour is mapped based on globalvectors and how the words relate to each other globally
								// in other words, if two words have a similar colour, then they must be decently related to each other
								// this colour is based on the ABSOLUTE global vectors, meaning the colour stays the same even if the same word shows up in different subreddit visualizations
								colour: [
									map(globalWordVectors[word.word][0], -4.5, 4.5, 0, 255), 
									map(globalWordVectors[word.word][1], -6, 3, 0, 255),
									map(globalWordVectors[word.word][2], -3, 4, 0, 255),
									255
								]
            });
						// add the BlobSphere to the metaball scene property
            metaball.scene.push(ball);
        }
        break;
    } 
    metaball.initializeBalls();
}

let metaball;

/** 
	* @method setup
	* @description p5.js setup function, sets up global variables, labels, and more
*/
function setup() {
    createCanvas(800, 600);
    background(120);
		// set up a metaball renderer
		metaball = new MetaBallRenderer({
			scene: [], 
				posX: 300, 
				posY: 300, 
				spacingX: 1, 
				spacingY: 1
		});
		
		// set up a title label
		title = new Label({
			text: "(Click me!)",
			x: width / 2,
			y: 50,
			outlineWeight: 2,
		})
		title.display();
	
		// setting up sliders
		blobSlider = createSlider(3, 20, wordBlobs, 1);
		blobSlider.position(20, height-20);
		blobSlider.size(width / 8);
		blobbiness = createSlider(0, 3, 1.3, 0.1);
		blobbiness.position(width-20 - width / 8, height-20);
		blobbiness.size(width / 8);
		pixelSpacing = createSlider(1, 3, 1, 1);
		pixelSpacing.position(20, 20);
		pixelSpacing.size(width / 8);
		
		// setting up the labels of sliders
		blobSliderLabel = new Label({
				text: " blobs",
				x: 20,
				y: height-20,
				fontSize: 16,
				align: LEFT,
		})
		blobbinessLabel = new Label({
				text: " field strength",
				x: width-20,
				y: height-20,
				fontSize: 16,
				align: RIGHT,
		})
		pixelSpacingLabel = new Label({
				text: " pixel spacing", 
				x: 20,
				y: 20,
				fontSize: 16,
				align: LEFT
		})
		
		// start the visualization!
		resetMetaball();
}

/** 
	* @method draw
	* @description p5.js draw function (every frame), draws metaball and updates labels
*/
function draw() {
		background(120);
    metaball.update();
		
		// title label alternates between subreddit title, and "(Click me!)"
		// in other words, it also functions as a button
		if (frameCount % 5 === 0) {
				if (title.text === "(Click me!)") {
						title.text = Object.keys(currSubredditSelection)[0];
				} else {
						title.text = "(Click me!)"
				}
		}
		title.display();
	
		// set the slider values and update their displays
		wordBlobs = blobSlider.value()
		blobSliderLabel.text = str(wordBlobs) + " blobs";
		blobSliderLabel.display();
	
		metaball.fieldStrength = blobbiness.value();
		blobbinessLabel.text = str(blobbiness.value()) + " field strength factor"
		blobbinessLabel.display();	
	
		metaball.spacingX = pixelSpacing.value();
		metaball.spacingY = pixelSpacing.value();
		pixelSpacingLabel.text = str(pixelSpacing.value()) + " pixel spacing"
		pixelSpacingLabel.display();	
		
		// increase the frame count
		frameCount += 1
}


/** 
	* @method mousePressed
	* @description p5.js mousePressed function, checks if mouse has clicked on button
*/
function mousePressed() {
		// if the detected mouse click was within the bounding box of the title object, then resetMetaball() and randomize a new one!
		if (mouseX < title.pos.x + title.width && mouseX > title.pos.x - title.width) {
				if (mouseY < title.pos.y + title.height && mouseY > title.pos.y - title.height) {
						resetMetaball();
				}
		}
}
