/**
 * @name         Subreddit Community Semantic Analysis
 * @description  Creating a data visualization that shows the most used words of each subreddit and how much they relate to one another 

 * @authour      James Lian
 * Created:      8-Oct-2025
 * Updated:      07-Dec-2025
*/


let wordBlobs = 10;

let balls = [];
let metaballs = [];

let redditDataTable;
let globalWordVectors = {}
let subreddits = {};

let sortedSubreddits = [];

let currSubredditSelection = {};

// UI VARIABLES
let title;
let frameCount = 0;
let blobSlider;
let blobSliderLabel;
let blobbiness;
let blobbinessLabel;
let pixelSpacing;
let pixelSpacingLabel;
let subredditSelect;
let allWordsSelect;
let prevSubredditSelection = "";
let recursionCheck;
let prevRecursionCheck = false;

// DATA HANDLING FUNCTIONS
function preload() {    
    // retrieving the 20 most popular words from some of the most popular subreddits, including the word vectors!
		// word vectors were generated by yours truly (James) through a custom Python script with a pretrained gloVe text embedding model
    redditDataTable = loadTable("subreddits.csv", "csv", "header", setupData);
}

/** 
	* @method setupData
	* @description Data preparation function that stores all necessary data inside the redditDataTable
*/
function setupData() {
	 console.log("Setting up data for " + str(redditDataTable.getRowCount()) + " rows");
	 let rows = redditDataTable.getRows();
	 // iterating through all the rows
    for (let i = 0; i < redditDataTable.getRowCount(); i++) {
        let row = rows[i];
				// storing important columns in variables
        let subreddit = row.getString("subreddit");
        let word = row.getString("word");
				
				// store all subreddits in the subreddits variable
        if (subreddits.hasOwnProperty(subreddit) === false) {
            subreddits[row.getString("subreddit")] = [];
        }

				// storing the relative vectors of the word (within their particular subreddit)
        let x = row.getString("relative_vector_x");
        let y = row.getString("relative_vector_y");
        let z = row.getString("relative_vector_z");
        // if word vectors are not invalid
        if (x !== "None" && y !== "None" && z !== "None") {
            x = float(x);
						y = float(y);
						z = float(z);
						subreddits[row.getString("subreddit")].push({
                "word": word,
                "relative_vector": [x, y, z], 
                "avg_score": int(row.getString("avg_score"))
            });
						
						// storing the global vectors of the word (within a global context - how they relate to ALL other words in ALL other subreddits in the .csv file)
            let globX = float(row.getString("absolute_vector_x"));
            let globY = float(row.getString("absolute_vector_y"));
            let globZ = float(row.getString("absolute_vector_z"));
            globalWordVectors[word] = [globX, globY, globZ];
        }
    }

	 sortedSubreddits = insertionSort(Object.keys(subreddits));
	 
} 

/** 
	* @method insertionSort
	* @description Utilizes the insertion sort algorithm to sort strings
	* Best case scenario will be O(n) - the algorithm is already sorted
   * Worst case scenario will be O(n^2) - the algorithm is in reverse order 
	* @param {Array} [arr] - The array to sort
*/
function insertionSort(arr) {
	for (let i = 1; i < arr.length; i++) {
		let key = arr[i];
		let j = i - 1;
		
		// Compare case-insensitively
		while (j >= 0 && arr[j].toLowerCase() > key.toLowerCase()) {
		  arr[j + 1] = arr[j];
		  j--;
		}
		arr[j + 1] = key;
	}
	return arr;
}

/** 
	* @method randomDataSelection
	* @description Randomly selects a subreddit and a randomized selection of its top words
*/
function randomDataSelection() {
		currSubredditSelection = {};

		// randomly select a subreddit and check if it has enough data points
		let selected = random(Object.keys(subreddits));
		if (subreddits[selected].length >= wordBlobs) {
				// shuffle the words and take the first few
				currSubredditSelection[selected] = shuffle(subreddits[selected]).slice(0, wordBlobs);
		}
}

/** 
	* @method resetMetaball
	* @description Resets the metaball parameters and generates a new metaball based on a randomized subreddit and its most popular words
	* @param {String} [selection] - The string that denotes the subreddit selected
*/
function resetMetaball(selection="") {
		// clear all the BlobSpheres inside the metaball's scene property
		metaball.scene.length = 0;
		
		// randomly select subreddit + words
		if (selection === "") {
			randomDataSelection();
		} else {
			currSubredditSelection = {};
			currSubredditSelection[selection] = shuffle(subreddits[selection]).slice(0, wordBlobs);
		}
		for (let subreddit in currSubredditSelection) {
				// instantiate new BlobSphere object as ball with relative_vector as its position prop and the avg_score of the word as its radius
				for (let word of currSubredditSelection[subreddit]) {
            let ball = new BlobSphere({
                x: word.relative_vector[0],
                y: word.relative_vector[1],
                z: word.relative_vector[2],
                radius: word.avg_score,
								text: word.word,
								// colour is mapped based on globalvectors and how the words relate to each other globally
								// in other words, if two words have a similar colour, then they must be decently related to each other
								// this colour is based on the ABSOLUTE global vectors, meaning the colour stays the same even if the same word shows up in different subreddit visualizations
								colour: [
									map(globalWordVectors[word.word][0], -4.5, 4.5, 0, 255), 
									map(globalWordVectors[word.word][1], -6, 3, 0, 255),
									map(globalWordVectors[word.word][2], -3, 4, 0, 255),
									255
								]
            });
						// add the BlobSphere to the metaball scene property
            metaball.scene.push(ball);
        }
        break;
    } 
    metaball.initializeBalls();

	 subredditSelect.selected(Object.keys(currSubredditSelection)[0])
	 prevSubredditSelection = subredditSelect.selected();
}

let metaball;

/** 
	* @method setup
	* @description p5.js setup function, sets up global variables, labels, and more
*/
function setup() {
    createCanvas(800, 600);
    background(120);
		// set up a metaball renderer
		metaball = new MetaBallRenderer({
			scene: [], 
				posX: 300, 
				posY: 300, 
				spacingX: 1, 
				spacingY: 1
		});
		
		// set up a title label
		title = new Label({
			text: "(Click me!)",
			x: width / 2,
			y: 50,
			outlineWeight: 2,
		})
		title.display();
	
		// setting up sliders
		blobSlider = createSlider(3, 20, wordBlobs, 1);
		blobSlider.position(20, height-20);
		blobSlider.size(width / 8);
		blobbiness = createSlider(0, 3, 1.3, 0.1);
		blobbiness.position(width-20 - width / 8, height-20);
		blobbiness.size(width / 8);
		pixelSpacing = createSlider(1, 3, 2, 1);
		pixelSpacing.position(20, 20);
		pixelSpacing.size(width / 8);
		
		// setting up the labels of sliders
		blobSliderLabel = new Label({
				text: " blobs",
				x: 20,
				y: height-20,
				fontSize: 16,
				align: LEFT,
		})
		blobbinessLabel = new Label({
				text: " field strength",
				x: width-20,
				y: height-20,
				fontSize: 16,
				align: RIGHT,
		})
		pixelSpacingLabel = new Label({
				text: " pixel spacing", 
				x: 20,
				y: 20,
				fontSize: 16,
				align: LEFT
		})

		subredditSelect = createSelect();
		for (let subreddit of sortedSubreddits) {
			subredditSelect.option(subreddit);
		}

		let allWords = [];
		allWordsSelect = createSelect();
		for (let subreddit of sortedSubreddits) {
			for (let word of subreddits[subreddit]) {
				allWords.push(word["word"]);
			}
		}
		allWords = Array.from(new Set(allWords));
		allWords = allWords.sort();
		for (let word of allWords) {
			allWordsSelect.option(word);
		}
	
		recursionCheck = createCheckbox();
		recursionCheck.position(width - 60, 20)
	
		// start the visualization!
		resetMetaball();
}

/** 
	* @method binarySearch
	* @description Utilizes binary search to search within a sorted algorithm to return the index of the element
	* Best case scenario will be O(1) - the element is exactly in the middle of the array
   * Worst case scenario will be O(log n) - the element is in the first position
	* @param {Array} [arr] - the sorted array
   * @param {String} [target] - the target string
*/
function binarySearch(arr, target) {
	let left = 0;
	let right = arr.length - 1;
	
	while (left <= right) {
		// Find the middle index
		let mid = Math.floor((left + right) / 2);
		
		// Compare case-insensitively
		let midVal = arr[mid].toLowerCase();
		let targetVal = target.toLowerCase();
		
		if (midVal === targetVal) {
		   return mid; // Found, return index
		} else if (midVal < targetVal) {
		   left = mid + 1; // Search right half
		} else {
		   right = mid - 1; // Search left half
		}
	}
	
	return -1; // Not found
}

/** 
	* @method linearSearch
	* @description Utilizes linear search to search within all the subreddits and return a matching array of a specified size
	* Best case scenario will be O(1) - the element is in first place
   * Worst case scenario will be O(n) - the element is last
   * @param {String} [target] - the target string
	* @param {Number} [size] - the size of the matching array
*/
function linearSearch(target, size=12) {
	let matching = {};

	for (let subreddit of sortedSubreddits) {
		if (Object.keys(matching).length === size) {
			return matching;
		}
		for (let word of subreddits[subreddit]) {
			if (Object.keys(matching).length === size) {
				return matching;
			}

			if (word["word"] === target) {
				matching[subreddit] = word["avg_score"];
				break;
			}
		}
	}
	return matching;
}

let network = {};
let networkMin = 10000000000000000000000;
let networkMax = -10000000000000000000000;
/** 
	* @method createRecursiveRelationNetwork
	* @description Uses recursion to create a relationship network between different subreddits
	* Big O Notation will always be O[n(n-1)]
	* @param {Object} [graph] - The graph representing all the subreddit's scores
   * @param {String} [start] - The starting subreddit
*/
function createRecursiveRelationNetwork(graph, start) {
	network[start] = {}
	for (let subreddit of Object.keys(graph)) {
		if (subreddit !== start) {
			network[start][subreddit] = Math.abs(graph[subreddit] - graph[start]);
			networkMin = Math.min(networkMin, Math.abs(graph[subreddit] - graph[start]));
			networkMax = Math.max(networkMax, Math.abs(graph[subreddit] - graph[start]));
		}
	}
	for (let subreddit of Object.keys(graph)) {
		if (!Object.keys(network).includes(subreddit)) {
			createRecursiveRelationNetwork(graph, subreddit);
			return;
		}
	}
}

/** 
	* @method getIndex
	* @description Another application of linear search that returns the index of the first matching element
	* Best case scenario will be O(1) - the element is in first place
   * Worst case scenario will be O(n) - the element is last
	* @param {Array} [arr] - the array to search through
   * @param {String} [target] - the target string
*/
function getIndex(arr, target) {
	let i = 0;
	for (let elem of arr) {
		if (elem === target) {
			return i;
		}
		i++;
	}
	return -1; // no matching element found
}

/** 
	* @method drawRecursiveNetwork
	* @description Draws a visualization of the network generated by createRecursiveRelationNetwork based on how closely related each community is
   * Closely related subreddits will have a line that curves to the outside. Lines that curve on the inside denote weak relationships
	* @param {Array} [radius] - the radius of the graph
*/
function drawRecursiveNetwork(radius=180) {
	let order = Object.keys(network);
	for (let i = 0; i < order.length; i++) {
		let iX = Math.cos(i / order.length * 2 * Math.PI) * radius;
		let iY = Math.sin(i / order.length * 2 * Math.PI) * radius;
		for (let node of Object.keys(network[order[i]])) {
			let nodeI = getIndex(order, node);
			if (nodeI !== i) {
				let fX = Math.cos(nodeI / order.length * 2 * Math.PI) * radius;
				let fY = Math.sin(nodeI / order.length * 2 * Math.PI) * radius;

				let cX1 = width/2 + (iX) * map(network[order[i]][node], networkMax, networkMin, 0, 2)
				let cY1 = height/2 - (iY) * map(network[order[i]][node], networkMax, networkMin, 0, 2)
				let cX2 = width/2 + (fX) * map(network[order[i]][node], networkMax, networkMin, 0, 2)
				let cY2 = height/2 - (fY) * map(network[order[i]][node], networkMax, networkMin, 0, 2)			
				stroke(0);
				noFill(0);
				strokeWeight(map(network[order[i]][node], networkMax, networkMin, 0, 2));
				bezier(width/2 + iX, height/2 - iY, cX1, cY1, cX2, cY2, width/2 + fX, height/2 - fY);

				fill(255);
			}
		}
		text(order[i], width/2 + iX - 30, width/2 - iY - 60)
	}
}

/** 
	* @method draw
	* @description p5.js draw function (every frame), draws metaball and updates labels
*/
function draw() {
	background(120);
	if (recursionCheck.checked()) {
		if (prevRecursionCheck !== recursionCheck.checked()) {
			network = {};
			weightedGraph = linearSearch(allWordsSelect.selected());
			createRecursiveRelationNetwork(weightedGraph, Object.keys(weightedGraph)[0]);
		}
		drawRecursiveNetwork();
		strokeWeight(1);
		text("Recursion On", width - 120, 60);
	} else {
		text("Recursion Off", width - 120, 60);
	   metaball.update();
	}
	prevRecursionCheck = recursionCheck.checked()
	
	// title label alternates between subreddit title, and "(Click me!)"
	// in other words, it also functions as a button
	if (frameCount % 30 === 0) {
		if (title.text === "(Click me!)") {
			title.text = `#${binarySearch(sortedSubreddits, Object.keys(currSubredditSelection)[0]) + 1}: ` + Object.keys(currSubredditSelection)[0];
		} else {
			title.text = "(Click me!)"
		}
	}
	title.display();

   if (prevSubredditSelection !== subredditSelect.selected()) {
	   resetMetaball(selection=subredditSelect.selected());
	   prevSubredditSelection = subredditSelect.selected();
   }
	// set the slider values and update their displays
	wordBlobs = blobSlider.value()
	blobSliderLabel.text = str(wordBlobs) + " blobs";
	blobSliderLabel.display();

	metaball.fieldStrength = blobbiness.value();
	blobbinessLabel.text = str(blobbiness.value()) + " field strength factor"
	blobbinessLabel.display();	

	metaball.spacingX = pixelSpacing.value();
	metaball.spacingY = pixelSpacing.value();
	pixelSpacingLabel.text = str(pixelSpacing.value()) + " pixel spacing"
	pixelSpacingLabel.display();	
	
	// increase the frame count
	frameCount += 1
}


/** 
	* @method mousePressed
	* @description p5.js mousePressed function, checks if mouse has clicked on button
*/
function mousePressed() {
		// if the detected mouse click was within the bounding box of the title object, then resetMetaball() and randomize a new one!
		if (mouseX < title.pos.x + title.width && mouseX > title.pos.x - title.width) {
				if (mouseY < title.pos.y + title.height && mouseY > title.pos.y - title.height) {
						resetMetaball();
				}
		}
}
